---
name: 3rdWeb/
description: ''
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: Contact@3rdwebcreator.com
mailchimp-list: ''
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  tim:
    name: Tim
    site: https://www.3rdwebcreator.com
    avatar: "/assets/images/avatar1.jpg"
    bio: A bio.
    email: email@site.com
    twitter: https://twitter.com/3rdwebcreator
  defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: tim
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
